config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  default_scope { order(created_at: :desc) }

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, only: [:show, :edit, :update, :destroy]

  def index
    @kittens = Kitten.all
    respond_to do |format|
      format.html
      format.json { render }
    end
  end

  def show
  end

  def new
    @kitten = Kitten.new
  end

  def edit
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten successfully created"
      redirect_to @kitten
    else
      flash.now[:danger] = "Something wrong"
      render :new
    end
  end

  def update
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Successfully updated"
      redirect_to @kitten
    else
      flash.now[:danger] = "Couldn't update"
      render :edit
    end
  end

  def destroy
    if @kitten.destroy
      flash[:success] = "Kitten was deleted"
    else
      flash[:danger] = "Unsuccessful"
    end
    redirect_to kittens_path
  end


  private


    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end

    def set_kitten
      @kitten = Kitten.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten.html.erb
<p>
<h4><%= link_to kitten.name, kitten %></h4>
Age : <%= kitten.age %><br>
Cuteness: <%= kitten.cuteness %><br>
Softness: <%= kitten.softness %><br>
</p>

app/views/kittens/_kitten_form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :age %>
  <br>
  <%= f.text_field :age %>
  <br>
  <%= f.label :cuteness %>
  <br>
  <%= f.text_field :cuteness %>
  <br>
  <%= f.label :softness %>
  <br>
  <%= f.text_field :softness %>
  <br>
  <%= f.submit "Submit" %>
<% end %>

app/views/kittens/_kitten_links.html.erb
<p>
<%= link_to "Edit", edit_kitten_path(@kitten) %> |
<%= link_to "Murder", kitten_path(@kitten), method: :delete, data: {confirm: "Meow?"} %>
</p>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render 'kitten_form' %>

app/views/kittens/index.html.erb
<h1>Kitten List</h1>
<%= link_to "New kitten", new_kitten_path %>
<%= render @kittens %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render 'kitten_form' %>

app/views/kittens/show.html.erb
<%= render @kitten %>
<%= render 'kitten_links' %>

app/views/layouts/_header.html.erb
<%= link_to "HOME", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |msg_type, msg| %>
      <%= content_tag :div, msg, class: msg_type %>
    <% end %>
    <%= yield %>
  </body>
</html>